encoding: utf-8
port: 4001
host: 127.0.0.1

# Site settings
title: Zhibin Gao
email: zhibingao@outlook.com

# 高志斌的个人博客
description: >

# the subpath of your site, e.g. /blog/
baseurl: ""

# the base hostname & protocol for your site
url: https://zhibingao.github.io

# Build settings
# 语法高亮
highlighter: rouge
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge

# relative_permalinks:true
# 博文的链接样式
permalink: /:year-:month-:day-:title.html

# 博客作者相关
author:
  name: Zhibin Gao
  email: zhibingao@outlook.com
  link: https://zhibingao.github.io
  github: https://github.com/zhibingao
  github_username: zhibingao
  github_repositories: https://github.com/zhibingao/zhibingao.github.io
  github_subscription: https://github.com/zhibingao/zhibingao.github.io/subscription

locals:
  tags: 标签
  about: 关于
  active: 技术

# 资源
favicon: /assets/images/favicon.ico
avatar: /assets/images/avatar.jpg
css: /assets/css/
js: /assets/js/
font: /assets/font/
images: /assets/images/
article: /assets/article/
pages: /pages/

# 页面
404: /pages/404.html
ie: /pages/ie.xml
# RSS
rss: /pages/rss.xml
# 网站地图
test: /pages/test.html
# 归档
archive: /pages/archive.html
# 链接
blogroll: /pages/blogroll.html
# 留言
message: /pages/message.html
# publications
publications: /pages/publications.html

# Disqus设置
disqus: 
id: Zhibin Gao
